variables:
  FRAMEWORK_CONTRIBUTION_SPACES: "@FRAMEWORK_CI_CONTRIBUTION_SPACES@"

stages:
 - build
 - deploy

### build (CMake project configuration)
build_framework:
  stage: build
  script:
    - chmod 700 ./share/ci/prepare_workspace.sh
    - chmod 700 ./share/ci/configure_framework.sh
    - ./share/ci/prepare_workspace.sh
    - ./share/ci/configure_framework.sh
    - chmod 700 ./share/ci/build_site.sh
    - ./share/ci/build_site.sh
    - chmod 700 ./share/ci/publish_site.sh
    - ./share/ci/publish_site.sh
  artifacts:
    paths:
    - public
  only:
    - master
  tags:
    - pid

### upload the static site (using gitlab pages)
pages:
  stage: deploy
  script:
    - echo "[PID] generating static web site"
  artifacts:
    paths:
    - public
  only:
    - master
  tags:
    - pid
